# SwiftLint configuration for rBUM
disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_count
  - empty_string
  - explicit_init
  - explicit_self
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - explicit_self
  - unused_import

included:
  - rBUM
  - Core
  - ResticService
excluded:
  - Carthage
  - Pods
  - .build
  - rBUMTests
  - rBUMUITests
  - CoreTests

# Customized rules
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 700
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - URL
    - URI

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - URL
    - url
    - app
    - log
    - to
    - at

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

custom_rules:
  explicit_failure_calls:
    name: "Explicit Failure Calls"
    regex: "(try|require)\\!\\s*\\("
    message: "Avoid using force unwrap with try or require"
    severity: warning

  protocol_property_accessors_order:
    name: "Protocol Property Accessors Order"
    regex: '(get set|set get)'
    message: "Protocol property accessors must be in the following order: get set"
    severity: warning

reporter: "xcode"
