# SwiftLint configuration for rBUM
disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - force_cast
  - force_try
  - force_unwrapping
  - implicit_return
  - redundant_string_enum_value
  - todo
  - trailing_comma
  - vertical_parameter_alignment
  - void_return

opt_in_rules:
  - closure_spacing
  - contains_over_filter_count
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - toggle_bool

analyzer_rules:
  - explicit_self
  - unused_import

included:
  - rBUM
  - Core
  - ResticService
excluded:
  - Carthage
  - Pods
  - .build
  - rBUMTests
  - rBUMUITests
  - CoreTests
  - "**/*.generated.swift"

# Customized rules
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 700
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 80
  error: 120

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - ID
    - URL
    - URI

identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - URL
    - url
    - app
    - log
    - to
    - at
    - i
    - j
    - k
    - x
    - y
    - z

nesting:
  type_level: 3

custom_rules:
  explicit_failure_calls:
    name: "Explicit Failure Calls"
    regex: "(try|require)\\!\\s*\\("
    message: "Avoid using force unwrap with try or require"
    severity: warning

  protocol_property_accessors_order:
    name: "Protocol Property Accessors Order"
    regex: '(get set|set get)'
    message: "Protocol property accessors must be in the following order: get set"
    severity: warning

reporter: "xcode"
